# Generated by Django 6.0.5 on 2026-05-16 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='uploads/')),
                ('hash_sha256', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('statut', models.CharField(choices=[('VALIDE', 'Validé et enregistré'), ('DOUBLON', 'Rejeté (Doublon exact)'), ('ATTENTE_VALIDATION', 'En attente de validation supérieur')], default='VALIDE', max_length=20)),
                ('score_similarite', models.FloatField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('fichier_similaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_fichiers.document')),
            ],
        ),
    ]
