POST http://127.0.0.1:8000/api/upload/
Content-Type: multipart/form-data; boundary=MonChantierBoundary

--MonChantierBoundary
Content-Disposition: form-data; name="file"; filename="chantiers.txt"
Content-Type: text/plain

Rapport de chantier : Les fondations à Abidjan sont prêtes.
--MonChantierBoundary--